name: Release

on:
  push:
    tags: ['*']

jobs:
    prebuild:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v3
      
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'

            - name: Setup environment
              run: npm install

            - name: Prebuild addon
              run: npm run prebuild

            - name: Prebuild upload
              run: prebuild --upload-all -u ${{ secrets.GITHUB_TOKEN }}