name: Release

on:
  push:
    tags: ['*']

jobs:
    build:
        runs-on: windows-2019

        steps:
            - uses: actions/checkout@v3
      
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'

            - name: Setup environment
              run: npm install

            - name: Prebuild addon
              run: npm run prebuild

            - name: Prebuild upload
              run: node_modules/.bin/prebuild.cmd --upload-all -u ${{ secrets.GITHUB_TOKEN }}

    publish:
        runs-on: windows-2019

        steps:
          - uses: actions/checkout@v3
    
          - uses: actions/setup-node@v3
            with:
              node-version: 18
              cache: 'npm'

          - name: Setup environment
            run: npm install

          - name: Publish package
            uses: mikeal/merge-release@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}